# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/auth/Projects/Serenity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/auth/Projects/Serenity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/auth/Projects/Serenity/CMakeFiles /home/auth/Projects/Serenity//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/auth/Projects/Serenity/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named discord_bot

# Build rule for target.
discord_bot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 discord_bot
.PHONY : discord_bot

# fast build rule for target.
discord_bot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/build
.PHONY : discord_bot/fast

src/commands/ban.o: src/commands/ban.cpp.o
.PHONY : src/commands/ban.o

# target to build an object file
src/commands/ban.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/ban.cpp.o
.PHONY : src/commands/ban.cpp.o

src/commands/ban.i: src/commands/ban.cpp.i
.PHONY : src/commands/ban.i

# target to preprocess a source file
src/commands/ban.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/ban.cpp.i
.PHONY : src/commands/ban.cpp.i

src/commands/ban.s: src/commands/ban.cpp.s
.PHONY : src/commands/ban.s

# target to generate assembly for a file
src/commands/ban.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/ban.cpp.s
.PHONY : src/commands/ban.cpp.s

src/commands/embed.o: src/commands/embed.cpp.o
.PHONY : src/commands/embed.o

# target to build an object file
src/commands/embed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/embed.cpp.o
.PHONY : src/commands/embed.cpp.o

src/commands/embed.i: src/commands/embed.cpp.i
.PHONY : src/commands/embed.i

# target to preprocess a source file
src/commands/embed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/embed.cpp.i
.PHONY : src/commands/embed.cpp.i

src/commands/embed.s: src/commands/embed.cpp.s
.PHONY : src/commands/embed.s

# target to generate assembly for a file
src/commands/embed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/embed.cpp.s
.PHONY : src/commands/embed.cpp.s

src/commands/kick.o: src/commands/kick.cpp.o
.PHONY : src/commands/kick.o

# target to build an object file
src/commands/kick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/kick.cpp.o
.PHONY : src/commands/kick.cpp.o

src/commands/kick.i: src/commands/kick.cpp.i
.PHONY : src/commands/kick.i

# target to preprocess a source file
src/commands/kick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/kick.cpp.i
.PHONY : src/commands/kick.cpp.i

src/commands/kick.s: src/commands/kick.cpp.s
.PHONY : src/commands/kick.s

# target to generate assembly for a file
src/commands/kick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/kick.cpp.s
.PHONY : src/commands/kick.cpp.s

src/commands/mute.o: src/commands/mute.cpp.o
.PHONY : src/commands/mute.o

# target to build an object file
src/commands/mute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/mute.cpp.o
.PHONY : src/commands/mute.cpp.o

src/commands/mute.i: src/commands/mute.cpp.i
.PHONY : src/commands/mute.i

# target to preprocess a source file
src/commands/mute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/mute.cpp.i
.PHONY : src/commands/mute.cpp.i

src/commands/mute.s: src/commands/mute.cpp.s
.PHONY : src/commands/mute.s

# target to generate assembly for a file
src/commands/mute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/mute.cpp.s
.PHONY : src/commands/mute.cpp.s

src/commands/unban.o: src/commands/unban.cpp.o
.PHONY : src/commands/unban.o

# target to build an object file
src/commands/unban.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/unban.cpp.o
.PHONY : src/commands/unban.cpp.o

src/commands/unban.i: src/commands/unban.cpp.i
.PHONY : src/commands/unban.i

# target to preprocess a source file
src/commands/unban.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/unban.cpp.i
.PHONY : src/commands/unban.cpp.i

src/commands/unban.s: src/commands/unban.cpp.s
.PHONY : src/commands/unban.s

# target to generate assembly for a file
src/commands/unban.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/unban.cpp.s
.PHONY : src/commands/unban.cpp.s

src/commands/unmute.o: src/commands/unmute.cpp.o
.PHONY : src/commands/unmute.o

# target to build an object file
src/commands/unmute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/unmute.cpp.o
.PHONY : src/commands/unmute.cpp.o

src/commands/unmute.i: src/commands/unmute.cpp.i
.PHONY : src/commands/unmute.i

# target to preprocess a source file
src/commands/unmute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/unmute.cpp.i
.PHONY : src/commands/unmute.cpp.i

src/commands/unmute.s: src/commands/unmute.cpp.s
.PHONY : src/commands/unmute.s

# target to generate assembly for a file
src/commands/unmute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/commands/unmute.cpp.s
.PHONY : src/commands/unmute.cpp.s

src/libs/cmdregistry.o: src/libs/cmdregistry.cpp.o
.PHONY : src/libs/cmdregistry.o

# target to build an object file
src/libs/cmdregistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/cmdregistry.cpp.o
.PHONY : src/libs/cmdregistry.cpp.o

src/libs/cmdregistry.i: src/libs/cmdregistry.cpp.i
.PHONY : src/libs/cmdregistry.i

# target to preprocess a source file
src/libs/cmdregistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/cmdregistry.cpp.i
.PHONY : src/libs/cmdregistry.cpp.i

src/libs/cmdregistry.s: src/libs/cmdregistry.cpp.s
.PHONY : src/libs/cmdregistry.s

# target to generate assembly for a file
src/libs/cmdregistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/cmdregistry.cpp.s
.PHONY : src/libs/cmdregistry.cpp.s

src/libs/dotenv.o: src/libs/dotenv.cpp.o
.PHONY : src/libs/dotenv.o

# target to build an object file
src/libs/dotenv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/dotenv.cpp.o
.PHONY : src/libs/dotenv.cpp.o

src/libs/dotenv.i: src/libs/dotenv.cpp.i
.PHONY : src/libs/dotenv.i

# target to preprocess a source file
src/libs/dotenv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/dotenv.cpp.i
.PHONY : src/libs/dotenv.cpp.i

src/libs/dotenv.s: src/libs/dotenv.cpp.s
.PHONY : src/libs/dotenv.s

# target to generate assembly for a file
src/libs/dotenv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/dotenv.cpp.s
.PHONY : src/libs/dotenv.cpp.s

src/libs/logger.o: src/libs/logger.cpp.o
.PHONY : src/libs/logger.o

# target to build an object file
src/libs/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/logger.cpp.o
.PHONY : src/libs/logger.cpp.o

src/libs/logger.i: src/libs/logger.cpp.i
.PHONY : src/libs/logger.i

# target to preprocess a source file
src/libs/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/logger.cpp.i
.PHONY : src/libs/logger.cpp.i

src/libs/logger.s: src/libs/logger.cpp.s
.PHONY : src/libs/logger.s

# target to generate assembly for a file
src/libs/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/libs/logger.cpp.s
.PHONY : src/libs/logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord_bot.dir/build.make CMakeFiles/discord_bot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... discord_bot"
	@echo "... src/commands/ban.o"
	@echo "... src/commands/ban.i"
	@echo "... src/commands/ban.s"
	@echo "... src/commands/embed.o"
	@echo "... src/commands/embed.i"
	@echo "... src/commands/embed.s"
	@echo "... src/commands/kick.o"
	@echo "... src/commands/kick.i"
	@echo "... src/commands/kick.s"
	@echo "... src/commands/mute.o"
	@echo "... src/commands/mute.i"
	@echo "... src/commands/mute.s"
	@echo "... src/commands/unban.o"
	@echo "... src/commands/unban.i"
	@echo "... src/commands/unban.s"
	@echo "... src/commands/unmute.o"
	@echo "... src/commands/unmute.i"
	@echo "... src/commands/unmute.s"
	@echo "... src/libs/cmdregistry.o"
	@echo "... src/libs/cmdregistry.i"
	@echo "... src/libs/cmdregistry.s"
	@echo "... src/libs/dotenv.o"
	@echo "... src/libs/dotenv.i"
	@echo "... src/libs/dotenv.s"
	@echo "... src/libs/logger.o"
	@echo "... src/libs/logger.i"
	@echo "... src/libs/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

